# Private options --------------------------------------------------------------
# It's best to overwrite these values in 'config-private.yaml'.

# Add your real Reddit username here.
userAgent: A bot by /u/<your real Reddit username goes here>
# The username for the bot.
username: username
# Its password.
password: password

# Other options ----------------------------------------------------------------

# The format of the response.
format: "{emote}{response}"
# Subreddit in which to look for comments.
subreddit: all
# PRAW comment_stream verbosity.
verbosity: 0
# Time to sleep between commenting.
commentSleepTime: 60
# Time to sleep on resetting due to errors.
resetSleepTime: 300
commentFrequency: 50
logUpdateTime: 10
